apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: kube
spec:
  selector:
    matchLabels:
      app: kube
  replicas: 2 # tells deployment to run 2 or more pods matching the template
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

  template:
    metadata:
      labels:
        app: kube
    spec:
      containers:
      - name: kube
        image: adekunmiolateju/development
        imagePullPolicy: Always
        ports:
        - containerPort: 8080