apiVersion: v1
kind: Service
metadata:
  name: kube-service
  labels:
    app: kube
spec:
  selector:
    app: kube
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30550